import { createElement } from 'lwc';
import FirstCmp_14July2022 from 'c/firstCmp_14July2022';

describe('c-first-cmp-14-july2022', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-first-cmp-14-july2022', {
            is: FirstCmp_14July2022
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});